# Generated by Django 5.2.4 on 2026-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
