# Generated by Codex on 2026-06-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_cloudinary_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="completeness_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="education_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="experience_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="keyword_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="overall_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="project_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="skills_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="years_of_experience",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="ResumeRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_recommendations",
            },
        ),
    ]
