# Generated by Codex on 2026-06-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0004_jobmatch_ats_analysis_fields"),
        ("resumes", "0003_resume_analysis_scores_recommendations"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                ("matching_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("recommendation_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_recommendations",
                "ordering": ("-match_score", "-updated_at"),
                "unique_together": {("resume", "job")},
            },
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["user", "is_active", "-match_score"],
                name="job_recomm_user_id_3a91b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["resume", "is_active"],
                name="job_recomm_resume__ef81e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["job", "is_active"],
                name="job_recomm_job_id_756b04_idx",
            ),
        ),
    ]
