# Generated by Django 5.2.4 on 2026-06-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobrecommendation',
            new_name='job_recomme_user_id_c43a75_idx',
            old_name='job_recomm_user_id_3a91b9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobrecommendation',
            new_name='job_recomme_resume__688745_idx',
            old_name='job_recomm_resume__ef81e7_idx',
        ),
        migrations.RenameIndex(
            model_name='jobrecommendation',
            new_name='job_recomme_job_id_dc8a19_idx',
            old_name='job_recomm_job_id_756b04_idx',
        ),
    ]
