# Generated by Django 5.2.4 on 2026-06-15 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0002_resume_cloudinary_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_sources',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME'), ('CONTRACT', 'CONTRACT'), ('INTERNSHIP', 'INTERNSHIP'), ('FREELANCE', 'FREELANCE'), ('REMOTE', 'REMOTE')], max_length=50)),
                ('experience_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('experience_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('apply_url', models.URLField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobsource')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='resumes.skill')),
            ],
            options={
                'db_table': 'job_skills',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_title_8402eb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company_name'], name='jobs_company_7fe7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_locatio_8650dd_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_is_acti_887823_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='jobs_posted__275cdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('job_source', 'external_job_id')},
        ),
    ]
