# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_searchkeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobmatch",
            name="education_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="project_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="resume_quality_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="recommendations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="improvement_suggestions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="match_category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
