# Generated by Codex on 2026-06-16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "structure_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "skills_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "experience_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "projects_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "keyword_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resume_scores",
            },
        ),
    ]

